# Generated by Django 4.2.16 on 2024-10-20 15:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-date', 'symbol'], 'verbose_name': 'Stock Data', 'verbose_name_plural': 'Stock Data'},
        ),
        migrations.AddField(
            model_name='stockdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the stock data'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(db_index=True, help_text='Stock symbol ', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.BigIntegerField(help_text='Volume of shares traded', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['symbol', 'date'], name='fetch_stock_symbol_55e7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['date'], name='fetch_stock_date_6325b9_idx'),
        ),
    ]
