# Generated by Django 4.2.16 on 2024-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_stock', '0002_alter_stockdata_options_stockdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
