# Generated by Django 4.2.16 on 2024-10-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_stock', '0003_alter_stockdata_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-date', 'symbol']},
        ),
    ]
