---
name: checks

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

jobs:
 test:
  name: Test
  runs-on: ubuntu-latest

  # services:
  #  db:
  #   image: postgres:latest
  #   env:
  #    POSTGRES_DB: your_db
  #    POSTGRES_USER: your_user
  #    POSTGRES_PASSWORD: your_password
  #   ports:
  #    - 5432:5432
  #   options: >-
  #    --health-cmd "pg_isready -U your_user"
  #    --health-interval 10s
  #    --health-timeout 5s
  #    --health-retries 5

  steps:
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

   - name: Checkout
     uses: actions/checkout@v2
   - name: Test
     run: |
      docker-compose run --rm app sh -c "python manage.py test"
