---
name: checks

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

jobs:
 test:
  name: Test
  runs-on: ubuntu-latest

  services:
   db:
    image: postgres:latest
    env:
     POSTGRES_DB: financial_data
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: adewale@2007
    ports:
     - 5432:5432

  steps:
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKERHUB_USER }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2

   - name: Install Docker Compose
     run: |
      sudo apt-get update
      sudo apt-get install -y docker-compose
   - name: Checkout
     uses: actions/checkout@v2
   - name: Test
     run: docker-compose run --rm app sh -c "python manage.py test"
